generate:
  - types
  - client

filter:
  tags:
    - ItemsService
  operations:
    # SystemService
    - getSystemInfoPublic
    # UserService
    - postUsersAuthenticatebyname
    # UserLibraryService
    - postUsersByUseridFavoriteitemsById
    - deleteUsersByUseridFavoriteitemsById
    # ArtistsService
    - getArtists
    - getArtistsByName
